/*
 * XYO RESTful Transaction Enrichment API
 *
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`enrich_transaction`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnrichTransactionError {
    Status429(models::ErrorResponse),
    Status4XX(models::ErrorResponse),
    Status5XX(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enrich_transactions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnrichTransactionsError {
    Status429(models::ErrorResponse),
    Status4XX(models::ErrorResponse),
    Status5XX(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_enrichment_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEnrichmentStatusError {
    Status429(models::ErrorResponse),
    Status4XX(models::ErrorResponse),
    Status5XX(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Enrich a single financial transaction synchronously.
pub async fn enrich_transaction(configuration: &configuration::Configuration, enrichment_request: models::EnrichmentRequest, x_correlation_id: Option<&str>, traceparent: Option<&str>) -> Result<models::EnrichmentResponse, Error<EnrichTransactionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_enrichment_request = enrichment_request;
    let p_header_x_correlation_id = x_correlation_id;
    let p_header_traceparent = traceparent;

    let uri_str = format!("{}/v1/ai/finance/enrichment/transaction", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_correlation_id {
        req_builder = req_builder.header("X-Correlation-ID", param_value.to_string());
    }
    if let Some(param_value) = p_header_traceparent {
        req_builder = req_builder.header("traceparent", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_enrichment_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnrichmentResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnrichmentResponse`")))),
        }
    } else {
        let headers = resp.headers().clone();
        let content = resp.text().await?;
        let entity: Option<EnrichTransactionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity, headers }))
    }
}

/// Enrich a collection of financial transactions asynchronously.
pub async fn enrich_transactions(configuration: &configuration::Configuration, enrich_transactions_request_inner: Vec<models::EnrichTransactionsRequestInner>, x_api_user: Option<&str>, x_correlation_id: Option<&str>, traceparent: Option<&str>) -> Result<models::EnrichTransactionCollectionResponse, Error<EnrichTransactionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_enrich_transactions_request_inner = enrich_transactions_request_inner;
    let p_header_x_api_user = x_api_user;
    let p_header_x_correlation_id = x_correlation_id;
    let p_header_traceparent = traceparent;

    let uri_str = format!("{}/v1/ai/finance/enrichment/transactions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_api_user {
        req_builder = req_builder.header("x-api-user", param_value.to_string());
    }
    if let Some(param_value) = p_header_x_correlation_id {
        req_builder = req_builder.header("X-Correlation-ID", param_value.to_string());
    }
    if let Some(param_value) = p_header_traceparent {
        req_builder = req_builder.header("traceparent", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_enrich_transactions_request_inner);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnrichTransactionCollectionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnrichTransactionCollectionResponse`")))),
        }
    } else {
        let headers = resp.headers().clone();
        let content = resp.text().await?;
        let entity: Option<EnrichTransactionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity, headers }))
    }
}

/// Get the status of an asynchronous bulk enrichment job.
pub async fn get_enrichment_status(configuration: &configuration::Configuration, id: &str, x_api_user: Option<&str>, x_correlation_id: Option<&str>, traceparent: Option<&str>) -> Result<models::EnrichmentCollectionStatusResponse, Error<GetEnrichmentStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_header_x_api_user = x_api_user;
    let p_header_x_correlation_id = x_correlation_id;
    let p_header_traceparent = traceparent;

    let uri_str = format!("{}/v1/ai/finance/enrichment/status/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_api_user {
        req_builder = req_builder.header("x-api-user", param_value.to_string());
    }
    if let Some(param_value) = p_header_x_correlation_id {
        req_builder = req_builder.header("X-Correlation-ID", param_value.to_string());
    }
    if let Some(param_value) = p_header_traceparent {
        req_builder = req_builder.header("traceparent", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnrichmentCollectionStatusResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnrichmentCollectionStatusResponse`")))),
        }
    } else {
        let headers = resp.headers().clone();
        let content = resp.text().await?;
        let entity: Option<GetEnrichmentStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity, headers }))
    }
}

